name: Run MC server

on:
  workflow_dispatch:

jobs:
  mcDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'deployment'
          
      - name: MC server container
        run: docker run -d -p 25565:25565 -e EULA=TRUE -e ONLINE_MODE=FALSE -e MODE=creative --name mc itzg/minecraft-server
      
      - run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        shell: bash
      - run: unzip -qq ngrok-stable-linux-amd64.zip
        shell: bash
      - run: ./ngrok authtoken ${{ secrets.NGROK_AUTHTOKEN }}
        shell: bash
      - run: ( ./ngrok tcp 25565 ) &
        shell: bash
        
      - name: Check Ngrok IP
        run: (echo -n "# Running on " && ( curl http://127.0.0.1:4040/api/tunnels | jq -r ".tunnels[0].public_url" | tail -c 21 ) ) > README.md
        shell: bash
      - name: Add & Commit URL
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: 'README.md'
          message: 'Updating ngrok URL'
          
      - name: Holding action
        run: sleep 30m
        timeout-minutes: 31
        
      - name: Stopping server
        run: docker exec mc rcon-cli stop
      - name: Deleting Ngrok URL
        if: always()
        run: ( echo -n "# Not running" ) > README.md
        shell: bash
      - name: Add & Commit Offline URL
        if: always()
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: 'README.md'
          message: 'Removing ngrok URL'

