name: Run MC server

on:
  workflow_dispatch:

jobs:
  mcDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'deployment'
          
      - name: MC server container
        run: docker run -d -p 25565:25565 -e EULA=TRUE -e ONLINE_MODE=FALSE -e MODE=creative --name mc itzg/minecraft-server
      
      - uses: luisboto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 1h
          port: 25565
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          tunnel_type: tcp
          save_url_to_filename: url.txt
        
      - name: Check Ngrok IP
        run: (echo -n "# Running on " && ( cat url.txt | tail -c 21 ) ) > README.md
        shell: bash
      - name: Add & Commit URL
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: 'README.md'
          message: 'Updating ngrok URL'
          
      - name: Holding action
        run: sleep 30m
        timeout-minutes: 31
        
      - name: Stopping server
        run: docker exec mc rcon-cli stop && docker attach mc
      - name: Deleting Ngrok URL
        if: always()
        run: ( echo -n "# Not running" ) > README.md
        shell: bash
      - name: Add & Commit Offline URL
        if: always()
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: 'README.md'
          message: 'Removing ngrok URL'

